ALTER TABLE works
ADD COLUMN IF NOT EXISTS author_display_names JSONB NOT NULL DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS author_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS max_author_cited_by_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS max_author_works_count INTEGER NOT NULL DEFAULT 0;
